### ISSUE TITLE
detected money: -1

### ISSUE THREAD

**Issue by monuzo** [ANRAR4/AutoBTD6#10]
hello
the money detection system isn't working sometimes with 1920x1080 (i'm also playing with my own 1920x1080 recorded map).
sometimes the detected money is -1 or sometimes it's not recognizing a number for example:
my real amount of money is 1,700 but it only recognizes 700.

**Comment by monuzo** [comment]
most of the time it doesn't recognize the '1'. from 1000-1999 it's -1. it starts working normal again from 2000-9999. From 10000 it doesn't recognize the 1 again.

**Comment by ANRAR4** [comment]
Could you provide screenshots of your game where the number does and does not get recognized correctly? (ideally using the included `py make_screenshot.py`)

**Comment by monuzo** [comment]
Here is the screenshot made with py make_screenshot.py and my console. Right when my score went above 1000 the console displayed -1.

![image](https://user-images.githubusercontent.com/113219885/223276622-22db4f59-01ee-4f50-b541-868a1a5bcb67.png)
![2023-03-07_00-03-09](https://user-images.githubusercontent.com/113219885/223276653-7bc7951a-e543-41dc-8085-90ef55f29cda.png)

**Comment by ANRAR4** [comment]
Apparently the positions of balance and live counter were slightly changed in the latest update(v35.0). The latest commit should fix the issues you were having.

**Comment by monuzo** [comment]
it works perfectly now, thanks!
