### ISSUE TITLE
screen BTD6_UNFOCUSED! when is on focus

### ISSUE THREAD

**Issue by VozDeOuro** [ANRAR4/AutoBTD6#11]
the terminal is on my second screen, and the game on full screen on my main 
what can i do to fix that ?

**Comment by ANRAR4** [comment]
Which version of BTD6 are you playing(i. e. steam or epic) or rather how is the BTD6 window called?

**Comment by VozDeOuro** [comment]
I'm playing steam version 
and the process name is 
BloonsTD6.exe

**Comment by ANRAR4** [comment]
Do you have AutoHotkey installed?
> Additionally the python ahk library requires AutoHotkey ([www.autohotkey.com](https://www.autohotkey.com/)) to be installed.

**Comment by VozDeOuro** [comment]
Yes i do

**Comment by ANRAR4** [comment]
If BTD6 really is the focussed window it should work then.

You cound test something like
```python
from ahk import AHK
import time

ahk = AHK()
time.sleep(3)
print(ahk.get_active_window().title.decode())
```
to see if the window title gets detected correctly.

**Comment by VozDeOuro** [comment]
> If BTD6 really is the focussed window it should work then.
> 
> You cound test something like
> 
> ```python
> from ahk import AHK
> import time
> 
> ahk = AHK()
> time.sleep(3)
> print(ahk.get_active_window().title.decode())
> ```
> 
> to see if the window title gets detected correctly. (for BTD6 it should output `BloonsTD6`)

i ran it on a different script, i don't know if was that what you mean, and it didn't work
![image](https://user-images.githubusercontent.com/36045463/232160336-c0ad0ade-6ccf-41bb-8912-062f840c7bf5.png)

**Comment by ANRAR4** [comment]
Which version of AutoHotkey and which version of the python ahk package are you using?

**Comment by VozDeOuro** [comment]
Python 3.7.9
AHK 2.0
pip AHK 0.14.2

**Comment by ANRAR4** [comment]
As far as i can tell AHK 2.0 is not yet supported by the python ahk package(https://github.com/spyoungtech/ahk/issues/183). So you would need to install AHK 1.x.

**Comment by VozDeOuro** [comment]
it works 
but its failing on the middle of the game

**Comment by ANRAR4** [comment]
Failing in the sense of losing all lives?
That may be due to balance changes that happend in some newer version. I did't test all playthroughs for the current version.
But you can record or adapt playthroughs yourself to make them work in the current version.

**Comment by VozDeOuro** [comment]
ok, thx for the fast help
