### ISSUE TITLE
Hero Selection Skips over Churchill

### ISSUE THREAD

**Issue by RobertHoueland** [ANRAR4/AutoBTD6#15]
For every hero after Obyn, the hero selector selects the hero *after* the hero it's supposed to.

**Example:**
Obyn is desired hero -> Obyn is selected as expected 
(same goes for first three heroes, they are selected as expected)

Churchill is desired hero -> Benjamin is selected 
(same goes for each hero after this, it selects the hero after them)

**Comment by ANRAR4** [comment]
Apparently the order inside the hero selection menu was modified at some point.
The latest commit should fix this issue
