### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable when running first replay

### ISSUE THREAD

**Issue by donttoutch** [ANRAR4/AutoBTD6#24]
Hey!

I installed the requirements, AHK (in path)
but when i try a replay command i always get the same error : 

![image](https://github.com/ANRAR4/AutoBTD6/assets/26526564/3a30afb8-9761-4ae8-a671-c30202a8cad7)

could you help me please?

**Comment by ANRAR4** [comment]
The command for replaying the file would be `python replay.py file candy_falls#alternate_bloons_rounds#2560x1440#noMK.btd6 -nomk`.
Does it work using the correct command?

**Comment by donttoutch** [comment]
yes my bad... Thanks for your help
