### ISSUE TITLE
Own replay error

### ISSUE THREAD

**Issue by LukysGaming** [ANRAR4/AutoBTD6#3]
Hi, I tried to record the gameplay using the provided tool, but when i try to run it i get this error, any idea what i did wrong?

`Traceback (most recent call last):
  File "D:\branch\AutoBTD6\replay.py", line 1218, in <module>
    main()
  File "D:\branch\AutoBTD6\replay.py", line 194, in main
    allAvailablePlaythroughs = getAllAvailablePlaythroughs(['own_playthroughs'], considerUserConfig=True)
  File "D:\branch\AutoBTD6\helper.py", line 538, in getAllAvailablePlaythroughs
    if considerUserConfig and not canUserUsePlaythrough({'filename': filename, 'fileConfig': fileConfig}):
  File "D:\branch\AutoBTD6\helper.py", line 478, in canUserUsePlaythrough
    mapConfig = parseBTD6InstructionsFile(playthrough['filename'])
  File "D:\branch\AutoBTD6\helper.py", line 224, in parseBTD6InstructionsFile
    newStep = {'action': 'upgrade', 'name': matches.group('name'), 'key': keybinds['path'][str(matches.group('path'))], 'pos': monkeys[matches.group('name')]['pos'], 'path': int(matches.group('path')), 'cost': adjustPrice(towers['monkeys'][monkeys[matches.group('name')]['type']]['upgrades'][int(matches.group('path'))][monkeyUpgrades[int(matches.group('path'))] - 1], newMapConfig['difficulty'], gamemode, {'action': 'upgrade', 'path': int(matches.group('path'))}, monkeys[matches.group('name')], matches.group('discount'))}
KeyError: 'hero'`

**Comment by LukysGaming** [comment]
+I have to remove every file in the `\own_playthroughs` or none of the replays will start and i will get the same error

**Comment by ANRAR4** [comment]
I guess you tried to upgrade a hero which isn't supported (as calculating the cost would be rather complex). The script was missing a type check for this case. Should be fixed with the latest commit (4db987c0aa38f018a5a2a02905fcb6b8525864fd)

**Comment by LukysGaming** [comment]
Yup thanks for quick fix, and i have one question, how am i supposed to make a replay on sanctuary? the thing keeps moving and the start move (to left or right) seems random

**Comment by LukysGaming** [comment]
Oh alr, last question, is there any special keybind to send lets say boomerang monkey's ability? or can i just click "1"? 
![image](https://user-images.githubusercontent.com/49752472/197623688-93d2f437-825b-4034-9f13-b8e9519708bc.png)

**Comment by ANRAR4** [comment]
> abilities can't be used as they require timing

Due to the fact that the replay of a playthrough works by determining if you have enough money available to perform the next action the script doesn't have any sense of timing (which may also vary depending on you pcs performance and RNG). So abilities can't be used. Furthermore their order (sorted by when they were made available) may differ after an update.

The best solution i could see would be something like `activate ability turbocharge 10s after round 40 starts` with images of each ability as resources. But I haven't implemented this yet either.

**Comment by LukysGaming** [comment]
If you could implement something like that in later updates it would be awesome, thanks for amazingly fast help (again). Thats everything i wanted to ask.
