### ISSUE TITLE
DLL porblem

### ISSUE THREAD

**Issue by justin111735** [ANRAR4/AutoBTD6#6]
when implement  this 

D:\AutoBTD6-main>py replay.py mm -mk -r
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 找不到指定的模組。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AutoBTD6-main\replay.py", line 2, in <module>
    from ocr import custom_ocr
  File "D:\AutoBTD6-main\ocr.py", line 3, in <module>
    import keras
  File "C:\Python\lib\site-packages\keras\__init__.py", line 21, in <module>
    from keras import models
  File "C:\Python\lib\site-packages\keras\models\__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "C:\Python\lib\site-packages\keras\engine\functional.py", line 24, in <module>
    import tensorflow.compat.v2 as tf
  File "C:\Python\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python\lib\site-packages\tensorflow\python\__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 找不到指定的模組。

I don't know which DLL missing 
Can I ask every pip's version .
here is my pip's version :
absl-py                      1.3.0
ahk                          0.14.2
astunparse                   1.6.3
cachetools                   5.2.0
certifi                      2022.12.7
charset-normalizer           2.1.1
flatbuffers                  22.12.6
gast                         0.4.0
google-auth                  2.15.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.51.1
h5py                         3.7.0
idna                         3.4
importlib-metadata           5.2.0
Jinja2                       3.1.2
keras                        2.11.0
keyboard                     0.13.5
libclang                     14.0.6
Markdown                     3.4.1
MarkupSafe                   2.1.1
MouseInfo                    0.1.3
numpy                        1.19.3
oauthlib                     3.2.2
opencv-python                4.6.0.66
opt-einsum                   3.3.0
packaging                    22.0
Pillow                       9.3.0
pip                          20.2.3
protobuf                     3.19.6
pyasn1                       0.4.8
pyasn1-modules               0.2.8
PyAutoGUI                    0.9.53
PyGetWindow                  0.0.9
PyMsgBox                     1.0.9
pyperclip                    1.8.2
PyRect                       0.2.0
PyScreeze                    0.1.28
pytweening                   1.0.4
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
setuptools                   49.2.1
six                          1.16.0
tensorboard                  2.11.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.11.0
tensorflow-estimator         2.11.0
tensorflow-intel             2.11.0
tensorflow-io-gcs-filesystem 0.29.0
termcolor                    2.1.1
typing-extensions            4.4.0
urllib3                      1.26.13
Werkzeug                     2.2.2
wheel                        0.38.4
wrapt                        1.14.1
zipp                         3.11.0

**Comment by ANRAR4** [comment]
Did you install Microsoft C++ Redistributable for Visual Studio 2015/2017/2019?
> The required packages also include Tensorflow which requires additional DLLs (Microsoft C++ Redistributable for Visual Studio [...]) to run.
