### ISSUE TITLE
break when starting 

### ISSUE THREAD

**Issue by razorthi** [ANRAR4/AutoBTD6#7]
So its hard to explain, but evrytime i try to start it works, but doesnt do what its supposed to.

What i mean by that is:
It keeps pressing esc so i get back to main screen and get "Do you want to quit"
![Screenshot 2023-02-03 175215](https://user-images.githubusercontent.com/97787406/216660937-7e213b21-bc56-4e5e-a206-1975518a0005.png)

**Comment by MigueldeHaroce** [comment]
The same thing happens to me, what is the solution?

Im in the epic version of btd6
![Screenshot 2024-04-06 025740](https://github.com/ANRAR4/AutoBTD6/assets/106353927/4314293b-90bb-40ed-ad06-3101bf7449f3)

**Comment by ANRAR4** [comment]
As stated in https://github.com/ANRAR4/AutoBTD6#supported-resolutions:
> Currently only screen resolutions of `1920x1080` and `2560x1440` are supported. Supporting a resolution requires the images in the folder `images/<resolution>` (as well as tested rescaled or native playthroughs).

**Comment by MigueldeHaroce** [comment]
Even if I manually put on the settings of windows to use 1920x1080?

**Comment by ANRAR4** [comment]
Yes, changing the game resolution doesn't work. The supported resolutions refer to a game resolution of `1920x1080` on a screen with a resolution of `1920x1080` and a game resolution of `2560x1440` on a screen with a resolution of `2560x1440`.
