### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

### ISSUE THREAD

**Issue by razorthi** [ANRAR4/AutoBTD6#8]
Not much to say the problem is that.
![Bild_2023-02-03_183819579](https://user-images.githubusercontent.com/97787406/216670284-6562da35-7b65-43d7-b9b7-00203d46084d.png)

**Comment by ANRAR4** [comment]
The `|` operator for two dictionaries is only available since Python 3.9. So I would assume you are using a version older than Python 3.9. Upgrading to Python 3.9 or higher should fix the issue.

**Comment by razorthi** [comment]
used 3.7 
but i found my own way to fix it 
![Bild_2023-02-04_123632842](https://user-images.githubusercontent.com/97787406/216765141-cd9ac156-6aa5-48f7-9f66-22b232f93d8a.png)
