### ISSUE TITLE
Own playthrough doesnt work

### ISSUE THREAD

**Issue by razorthi** [ANRAR4/AutoBTD6#9]
So i made a playthrough for the new expert map, but it doesnt work for some reason 
![Bild_2023-02-25_223725430](https://user-images.githubusercontent.com/97787406/221380728-3f80994a-6715-4a59-baca-bebe697d9c58.png)

hero      etienne 
map     dark dungeons 
mode    easy

Code is:

place etienne hero0 at 763, 1282
place sub sub0 at 1827, 1150
upgrade sub0 path 0
upgrade sub0 path 0
place dart dart0 at 326, 1064
upgrade dart0 path 2
upgrade dart0 path 2
upgrade dart0 path 2
upgrade dart0 path 0
upgrade dart0 path 0
place dart dart1 at 2137, 1177
upgrade dart1 path 2
upgrade dart1 path 2
upgrade dart1 path 2
upgrade dart1 path 0
upgrade dart1 path 0
upgrade sub0 path 1
upgrade sub0 path 1
upgrade sub0 path 1
upgrade dart0 path 2
upgrade dart1 path 2
retarget sub0
retarget sub0
retarget sub0
place dart dart2 at 995, 1272
upgrade dart2 path 2
upgrade dart2 path 2
upgrade dart2 path 2
upgrade dart2 path 0
upgrade dart2 path 0
upgrade dart2 path 2
upgrade sub0 path 1
place bomb bomb0 at 1229, 1318
upgrade bomb0 path 1
upgrade bomb0 path 1
upgrade bomb0 path 1
upgrade bomb0 path 1
upgrade bomb0 path 0
upgrade bomb0 path 0

**Comment by ANRAR4** [comment]
You may need to add the `-nv` flag as an argument, so non validated playthroughs(including those you recorded yourself) get considered. Alternatively you could run the playthrough in `validate` mode or modify `playthrough_stats.json` to include your map with `"validation_result": true` for your resolution.

**Comment by razorthi** [comment]
pretty suree it works now thank you
